from . import help
from . import start
from . import reklama
from . import prayerTimes
from . import tarjimon
from . import imloHandler
from . import speakHandler
from . import wikipedia
from . import krill_latin
from . import echo